module.exports=function createTalhaRunnerRuntime(ctx){
const app=ctx.app,ScriptLanguage=ctx.ScriptLanguage,UndoModes=ctx.UndoModes,core=ctx.core,MAX_HISTORY=20,FAVORITES_KEY="talhaRunnerV2Favorites",SEEN_KEY="talhaRunnerSeenUpdate",SKIP_KEY="talhaRunnerSkippedUpdate";let history=[],listeners=[],latest=null,checkTimer=null;
function on(el,e,h){if(!el)return;el.addEventListener(e,h);listeners.push([el,e,h]);}function el(id){return document.getElementById(id);}function store(k,v){try{localStorage.setItem(k,v);}catch(e){}}function load(k){try{return localStorage.getItem(k)||"";}catch(e){return"";}}
function applyUi(){
const style=document.createElement("style");style.id="talhaRuntimeTheme";style.textContent=`
html,body{background:#17191f!important;color:#f7f8fb!important}.runner{padding:12px!important;gap:9px!important;background:linear-gradient(145deg,#17191f,#20242d)!important}.header{min-height:48px!important;flex-basis:48px!important;padding:6px 8px!important;border:1px solid #343946!important;border-radius:10px!important;background:#222630!important}.title{font-size:16px!important;letter-spacing:.8px!important;color:#fff!important}.version{font-size:10px!important;color:#aeb6c6!important;white-space:nowrap!important}.header-right{gap:8px!important}.update-status{max-width:145px!important;color:#aeb6c6!important}.editor-wrap{min-height:100px!important}#codeInput{border:1px solid #3d4352!important;border-radius:10px!important;background:#111318!important;color:#f5f7fb!important;padding:12px!important;font-size:12px!important;line-height:1.5!important}#codeInput:focus{border-color:#6ea8ff!important}button{border:1px solid #4b5263!important;border-radius:9px!important;background:#303541!important;color:#fff!important;font-weight:600!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}button:hover{background:#3a4050!important}#runButton{background:#355fd6!important;border-color:#5d80e8!important}#clearButton{background:#3b404b!important}.status{border:1px solid #343946!important;border-radius:9px!important;background:#1d2027!important;min-height:30px!important}.bottom{gap:7px!important;flex-basis:34px!important}.bottom button{height:34px!important;font-size:10px!important;padding:0 5px!important}#saveFavoriteButton{background:#74571c!important;border-color:#a77d29!important}#favoritesButton{background:#245b75!important;border-color:#3681a3!important}#historyButton{background:#653a72!important;border-color:#9253a4!important}#updateButton{background:#256342!important;border-color:#39915f!important}#notificationCard{border:1px solid #3d4557!important;border-radius:10px!important;background:#222731!important;padding:10px!important}.notice-title{color:#fff!important}.notice-actions button:first-child{background:#345d9d!important}.notice-actions button:last-child{background:#59435f!important}
#bellButton{font-size:0!important;background:#292e38!important;border-color:#4a5262!important;position:relative!important;overflow:visible!important}#bellButton .runtimeBell{display:block!important;position:absolute!important;left:9px!important;top:7px!important;width:12px!important;height:13px!important;border:2px solid #dce3ef!important;border-radius:7px 7px 4px 4px!important;border-top-color:#dce3ef!important}#bellButton .runtimeBell:after{content:"";position:absolute;left:3px;bottom:-5px;width:4px;height:3px;border-radius:0 0 4px 4px;background:#dce3ef}#bellButton.unread{border-color:#ff5d68!important;box-shadow:0 0 0 1px #ff5d68 inset!important}#bellDot{background:#ff4d5b!important;width:7px!important;height:7px!important;right:3px!important;top:3px!important}
`;document.head.appendChild(style);
const bell=el("bellButton");if(bell){bell.textContent="";const shape=document.createElement("span");shape.className="runtimeBell";bell.appendChild(shape);const dot=document.createElement("span");dot.id="bellDot";bell.appendChild(dot);}
const title=document.querySelector(".title");if(title)title.textContent="TALHA RUNNER";
}
function initialize(){applyUi();const code=el("codeInput"),run=el("runButton"),clear=el("clearButton"),clearAfter=el("clearAfterRun"),status=el("statusText"),historyBtn=el("historyButton"),saveBtn=el("saveFavoriteButton"),favBtn=el("favoritesButton"),updateBtn=el("updateButton"),version=el("versionText"),updateStatus=el("updateStatus"),bell=el("bellButton"),card=el("notificationCard"),noticeTitle=el("notificationTitle"),noticeSummary=el("notificationSummary"),details=el("detailsButton"),skip=el("skipButton");if(!code||!run)throw new Error("Runner arayüzü bulunamadı");
function setStatus(m){if(status)status.textContent=m;}function refreshVersion(){if(version)version.textContent="V2 • "+core.getRuntimeVersion()+"  |  Core "+core.getCoreVersion();if(updateStatus)updateStatus.textContent="● Güncel";}refreshVersion();
function addHistory(c){if(c&&history[0]!==c){history.unshift(c);if(history.length>MAX_HISTORY)history.pop();}}function focus(){try{code.focus();}catch(e){}}function restore(){try{if(app.activeWindow&&app.activeWindow.activate)app.activeWindow.activate();}catch(e){}}
function runCode(){const c=code.value;if(!c||!c.replace(/\s/g,""))return setStatus("Kod alanı boş");setStatus("Çalıştırılıyor...");try{app.doScript(c,ScriptLanguage.JAVASCRIPT,undefined,UndoModes.ENTIRE_SCRIPT,"Talha Runner V2");addHistory(c);setStatus("✓ Tamamlandı");if(clearAfter&&clearAfter.checked)code.value="";}catch(e){setStatus("✕ "+(e&&e.message?e.message:String(e)));}finally{restore();}}
function loadFav(){try{const p=JSON.parse(localStorage.getItem(FAVORITES_KEY)||"[]");return Array.isArray(p)?p:[];}catch(e){return[];}}function saveFav(a){localStorage.setItem(FAVORITES_KEY,JSON.stringify(a));}
function saveCurrent(){const c=code.value;if(!c||!c.replace(/\s/g,""))return setStatus("Favoriye kaydedilecek kod yok");const n=prompt("Favori adı:","");if(n===null||!String(n).trim())return;const name=String(n).trim(),a=loadFav();let i=a.findIndex(x=>String(x.name).toLocaleLowerCase()===name.toLocaleLowerCase());if(i>=0){if(!confirm("'"+a[i].name+"' zaten var. Üzerine yazılsın mı?"))return;a[i]={name,code:c};}else a.push({name,code:c});saveFav(a);setStatus("★ Favoriye kaydedildi: "+name);}
function showFav(){let a=loadFav();if(!a.length)return setStatus("Favoriler boş");let m="FAVORİLER\n\n";a.forEach((x,i)=>m+=(i+1)+". "+x.name+"\n");m+="\nNumara = yükle | R3 = yeniden adlandır | S3 = sil";const s=prompt(m,"1");if(s===null)return;const z=String(s).trim(),r=/^R(\d+)$/i.exec(z),d=/^S(\d+)$/i.exec(z);if(r){const i=Number(r[1])-1;if(!a[i])return;const n=prompt("Yeni favori adı:",a[i].name);if(n&&String(n).trim()){a[i].name=String(n).trim();saveFav(a);setStatus("Favori yeniden adlandırıldı");}return;}if(d){const i=Number(d[1])-1;if(a[i]&&confirm("'"+a[i].name+"' favorisi silinsin mi?")){const n=a[i].name;a.splice(i,1);saveFav(a);setStatus("Favori silindi: "+n);}return;}if(/^\d+$/.test(z)&&a[Number(z)-1]){const x=a[Number(z)-1];code.value=x.code;setStatus("★ Favoriden yüklendi: "+x.name);focus();}}
function showHistory(){if(!history.length)return setStatus("Geçmiş boş");let m="SON ÇALIŞTIRILAN KODLAR\n\n";history.forEach((x,i)=>m+=(i+1)+". "+x.replace(/[\r\n]/g," ").slice(0,60)+"\n");const s=prompt(m,"1");if(s!==null&&/^\d+$/.test(String(s).trim())&&history[Number(s)-1]!==undefined){code.value=history[Number(s)-1];focus();}}
function renderNotice(info){latest=info;if(!info.available){bell.classList.remove("unread");if(card)card.classList.remove("visible");if(updateStatus)updateStatus.textContent="● Güncel";return;}if(load(SKIP_KEY)===info.version){bell.classList.remove("unread");return;}if(load(SEEN_KEY)!==info.version)bell.classList.add("unread");if(noticeTitle)noticeTitle.textContent="Yeni sürüm: "+info.version;if(noticeSummary)noticeSummary.textContent=info.summary||"Yeni sürüm mevcut.";if(updateStatus)updateStatus.textContent="● Güncelleme var";}
async function silentCheck(){try{renderNotice(await core.checkForUpdate());}catch(e){}}
async function openBell(){try{renderNotice(await core.checkForUpdate());}catch(e){}if(!latest||!latest.available){setStatus("Yeni bildirim yok");return;}store(SEEN_KEY,latest.version);bell.classList.remove("unread");card.classList.toggle("visible");}
function showDetails(){if(!latest)return;let m=(latest.title||("TALHA RUNNER "+latest.version))+"\n\n"+(latest.summary||"")+"\n";if(latest.notes&&latest.notes.length)m+="\nYENİLİKLER / DÜZELTMELER\n• "+latest.notes.join("\n• ");alert(m);}
function skipVersion(){if(!latest||!latest.available)return;store(SKIP_KEY,latest.version);store(SEEN_KEY,latest.version);bell.classList.remove("unread");card.classList.remove("visible");setStatus("Bu sürüm atlandı: "+latest.version);}
async function update(){setStatus("Güncelleme kontrol ediliyor...");updateBtn.disabled=true;try{const info=await core.checkForUpdate();if(!info.available){refreshVersion();setStatus("✓ Zaten güncel: "+core.getRuntimeVersion());return;}setStatus("İndiriliyor ve doğrulanıyor...");const r=await core.checkAndInstallUpdate();if(r.updated){store(SEEN_KEY,r.version);store(SKIP_KEY,"");setTimeout(()=>{const v=el("versionText");if(v)v.textContent="V2 • "+core.getRuntimeVersion()+"  |  Core "+core.getCoreVersion();const u=el("updateStatus");if(u)u.textContent="● Güncel";const s=el("statusText");if(s)s.textContent="✓ Güncellendi: "+r.version;},50);}}catch(e){setStatus("✕ Güncelleme başarısız: "+(e.message||e));}finally{updateBtn.disabled=false;}}
if(updateBtn)updateBtn.textContent="Güncelle";on(run,"click",runCode);on(clear,"click",()=>{code.value="";setStatus("Hazır");focus();});on(code,"keydown",e=>{if(e.ctrlKey&&e.key==="Enter"){e.preventDefault();runCode();}});on(saveBtn,"click",saveCurrent);on(favBtn,"click",showFav);on(historyBtn,"click",showHistory);on(updateBtn,"click",update);on(bell,"click",openBell);on(details,"click",showDetails);on(skip,"click",skipVersion);setStatus("Hazır");setTimeout(silentCheck,800);checkTimer=setInterval(silentCheck,300000);
}
function dispose(){if(checkTimer){clearInterval(checkTimer);checkTimer=null;}listeners.forEach(x=>{try{x[0].removeEventListener(x[1],x[2]);}catch(e){}});listeners=[];const s=document.getElementById("talhaRuntimeTheme");if(s&&s.parentNode)s.parentNode.removeChild(s);}
return{initialize,dispose};};
